apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-example-deployment
  namespace: webhook-example
  labels:
    app: sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-example
  template:
    metadata:
      labels:
        app: admission-webhook-example
    spec:
      containers:
        - name: admission-webhook-example
          image: harbor.jwell56.com/dev/admission-webhook-example:v1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - -port=443
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-example-certs
